In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout,  Flatten
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('dadosdesonar.csv')
df.head()

,attribute_1,attribute_2,attribute_3,attribute_4,attribute_5,attribute_6,attribute_7,attribute_8,attribute_9,attribute_10,...,attribute_52,attribute_53,attribute_54,attribute_55,attribute_56,attribute_57,attribute_58,attribute_59,attribute_60,Class
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,Rock
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,Rock
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,Rock
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,Rock
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,Rock

In [4]:
X_input = df.iloc[: , :-1]
y_label = df['Class'].values

In [5]:
label_encoder_Y = LabelEncoder()
y_label = label_encoder_Y.fit_transform(y_label)
y_label = y_label.reshape([208, 1])

In [6]:
modelo = Sequential()
modelo.add(Dense(300, input_dim=60, activation = 'relu'))
modelo.add(Dense(200, activation = 'relu'))
modelo.add(Dense(100, activation = 'relu'))
modelo.add(Dense(1, activation = 'sigmoid'))
modelo.compile (optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
modelo.fit (X_input, y_label, epochs=30)

Epoch 1/30
7/7 [==============================] - 1s 8ms/step - loss: 0.6825 - accuracy: 0.5240
Epoch 2/30
7/7 [==============================] - 0s 7ms/step - loss: 0.6341 - accuracy: 0.7260
Epoch 3/30
7/7 [==============================] - 0s 7ms/step - loss: 0.5911 - accuracy: 0.7067
Epoch 4/30
7/7 [==============================] - 0s 8ms/step - loss: 0.5486 - accuracy: 0.7404
Epoch 5/30
7/7 [==============================] - 0s 6ms/step - loss: 0.4886 - accuracy: 0.7596
Epoch 6/30
7/7 [==============================] - 0s 5ms/step - loss: 0.4523 - accuracy: 0.8173
Epoch 7/30
7/7 [==============================] - 0s 4ms/step - loss: 0.4175 - accuracy: 0.8125
Epoch 8/30
7/7 [==============================] - 0s 4ms/step - loss: 0.3694 - accuracy: 0.8558
Epoch 9/30
7/7 [==============================] - 0s 4ms/step - loss: 0.3503 - accuracy: 0.8365
Epoch 10/30
7/7 [==============================] - 0s 4ms/step - loss: 0.3299 - accuracy: 0.8654
Epoch 11/30
7/7 [==============================] - 0s 7ms/step - loss: 0.3000 - accuracy: 0.8654
Epoch 12/30
7/7 [==============================] - 0s 5ms/step - loss: 0.2666 - accuracy: 0.9279
Epoch 13/30
7/7 [==============================] - 0s 5ms/step - loss: 0.2605 - accuracy: 0.8798
Epoch 14/30
7/7 [==============================] - 0s 7ms/step - loss: 0.3163 - accuracy: 0.8606
Epoch 15/30
7/7 [==============================] - 0s 7ms/step - loss: 0.2602 - accuracy: 0.8606
Epoch 16/30
7/7 [==============================] - 0s 7ms/step - loss: 0.2165 - accuracy: 0.9375
Epoch 17/30
7/7 [==============================] - 0s 7ms/step - loss: 0.2167 - accuracy: 0.9279
Epoch 18/30
7/7 [==============================] - 0s 7ms/step - loss: 0.1934 - accuracy: 0.9231
Epoch 19/30
7/7 [==============================] - 0s 8ms/step - loss: 0.1667 - accuracy: 0.9471
Epoch 20/30
7/7 [==============================] - 0s 12ms/step - loss: 0.1400 - accuracy: 0.9663
Epoch 21/30
7/7 [==============================] - 0s 8ms/step - loss: 0.1216 - accuracy: 0.9760
Epoch 22/30
7/7 [==============================] - 0s 11ms/step - loss: 0.1063 - accuracy: 0.9808
Epoch 23/30
7/7 [==============================] - 0s 7ms/step - loss: 0.0917 - accuracy: 0.9808
Epoch 24/30
7/7 [==============================] - 0s 7ms/step - loss: 0.0772 - accuracy: 0.9808
Epoch 25/30
7/7 [==============================] - 0s 7ms/step - loss: 0.1023 - accuracy: 0.9760
Epoch 26/30
7/7 [==============================] - 0s 7ms/step - loss: 0.1300 - accuracy: 0.9375
Epoch 27/30
7/7 [==============================] - 0s 11ms/step - loss: 0.1086 - accuracy: 0.9663
Epoch 28/30
7/7 [==============================] - 0s 7ms/step - loss: 0.1063 - accuracy: 0.9567
Epoch 29/30
7/7 [==============================] - 0s 7ms/step - loss: 0.0825 - accuracy: 0.9760
Epoch 30/30
7/7 [==============================] - 0s 7ms/step - loss: 0.0706 - accuracy: 0.9904

In [7]:
modelo.evaluate (X_input, y_label)

7/7 [==============================] - 0s 3ms/step - loss: 0.0808 - accuracy: 0.9760

[0.08084522932767868, 0.9759615659713745]